apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-deployment
  namespace: nodejs
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapp
        env: dev
        color: blue
    spec:
      containers:
      - name: nodeapp
        image: tarun/nodejs-v1
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        ports:
        - containerPort: 3000
