apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
  namespace: nodejs
  labels:
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodeapp
    env: dev
    color: green
